/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaControlador;

import Modelos.DB;
import Modelos.Vehiculo;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Evelin
 */
public class Buscar extends javax.swing.JFrame {

    public Parqueadero parqueadero;
    public String action = "";
    
    public Buscar() {
        initComponents();
    }
    
    /**
     * Crear una ventana de busqueda con la posibilidad de tener los datos del parqueadero
     * @param parqueadero 
     * @author Diego
     */
    public Buscar(Parqueadero parqueadero) {
        //igualar la varible local a la dada
        this.parqueadero = parqueadero;
        initComponents();
    }
    
    /**
     * Crear una ventana de buscar con una accion especifica dada, actualmente puede recibir el valor "actualiar"
     * @param action
     * @author Diego
     */
    public Buscar(String action) {
        initComponents();
        //igualar la varible local con la dada
        this.action = action;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parquederoNombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        placaTxt = new javax.swing.JTextField();
        buscarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        parquederoNombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        parquederoNombre.setText("Parqueadero c.c");

        jLabel1.setText("Placa");

        buscarBtn.setText("Buscar");
        buscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(parquederoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addGap(88, 88, 88)
                        .addComponent(placaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(buscarBtn)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(parquederoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(placaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(buscarBtn)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
        //buscar si existe un vehiculo con la placa ingresada
        
        //crear intancia de la clase DB
        DB db = new DB();
        
        try {
            //buscar el vehiculo con la placa
            Vehiculo veh = db.buscar(placaTxt.getText());
            
            //comprobar si el vehiculo existe
            if(veh == null) {
                //si el vehiculo NO existe
                
                //si se dio la accion "actualizar"
                if(action.equals("actualizar")) {
                    //mostrar mensaje indicando que el vehiculo no existe
                    JOptionPane.showMessageDialog(this, "El vehiculo no existe");
                    return; //parar el metodo aqui
                }
                //si NO se dio la accion
                
                //crear un formulario de vehiculo dandole la placa disponible y la informacion del parqueadero
                FormularioVehiculo fVehiculo = new FormularioVehiculo(placaTxt.getText(), this.parqueadero);
                fVehiculo.setVisible(true);
            } else {
                //SI el vehiculo SI EXISTE
                
                //si se dio la accion de actualizar
                if(action.equals("actualizar")) {
                    //abrir una ventana de formulario de vehiculo con la informacion del vehiculo encontrado y la accion actualizar
                    FormularioVehiculo fVehiculo = new FormularioVehiculo(veh, action);
                    fVehiculo.setVisible(true);
                    return; //parar el flujo del metodo aqui
                }
                
                //si NO se dio la accion actualizar
                
                //abrir una ventana de confirmacion de ingreso ya que el vehiculo ya existe y no tiene que ser creado
                FormularioConfirmacion fConfirmacion = new FormularioConfirmacion(veh, this.parqueadero);
                fConfirmacion.setVisible(true);
            }           
        } catch (IOException ex) {
            Logger.getLogger(Parqueadero.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Parqueadero.class.getName()).log(Level.SEVERE, null, ex);
        }
        //cerrar esta ventana de busqueda
        this.setVisible(false);
    }//GEN-LAST:event_buscarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel parquederoNombre;
    private javax.swing.JTextField placaTxt;
    // End of variables declaration//GEN-END:variables
}
