/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaControlador;

import Modelos.Carro;
import Modelos.Cubiculo;
import Modelos.Moto;
import Modelos.Vehiculo;
import java.util.Date;

/**
 *
 * @author Evelin
 */
public class FormularioConfirmacion extends javax.swing.JFrame {

    /**
     * Creates new form FormularioConfirmacion
     */
    
    public Vehiculo vehiculo = null;
    public Parqueadero parqueadero = null;
    
    public FormularioConfirmacion() {
        initComponents();
    }
    
    /**
     * Crear una ventana de confirmacion de ingreso al parqueadero con el vehiculo a ingresar y el parqueadero
     * @param vehiculo
     * @param parqueadero 
     * @author Diego
     */
    public FormularioConfirmacion(Vehiculo vehiculo, Parqueadero parqueadero) {
         initComponents();
         //igualar varibles locales con las dadas
         this.vehiculo = vehiculo;
         this.parqueadero = parqueadero;
         //lamar metodo que rellena los campos
         IniciarCampos();
    }
    
    /**
     * Rellenar campos de la interfaz con los datos basicos del vehiculo
     * @author Diego
     */
    public void IniciarCampos() {
        //desactivar y rellenar campos
        this.placaTxt.setEnabled(false);
        this.placaTxt.setText(vehiculo.getPlaca());
        this.nombreTxt.setEnabled(false);
        this.nombreTxt.setText(vehiculo.getConductor().getNombre());
        
        this.carroRbn.setEnabled(false);
        this.motoRbn.setEnabled(false);
        
        this.cascosTxt.setEnabled(false);
        this.remolqueCheck.setEnabled(false);
        
        if(this.vehiculo instanceof Carro) {
            this.carroRbn.setSelected(true);  
            this.remolqueCheck.setSelected(((Carro)this.vehiculo).isRemolque());
        } else {
            this.motoRbn.setSelected(true);
            this.cascosTxt.setText(String.valueOf(((Moto) this.vehiculo).getNroCascos()));
        }     
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parquederoNombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        placaTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        carroRbn = new javax.swing.JRadioButton();
        motoRbn = new javax.swing.JRadioButton();
        remolqueCheck = new javax.swing.JCheckBox();
        cascosTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        confirmarBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        parquederoNombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        parquederoNombre.setText("Parqueadero c.c");

        jLabel1.setText("Placa");

        jLabel2.setText("Nombre Dueño");

        jLabel3.setText("Tipo Vehiculo");

        carroRbn.setText("Carro");
        carroRbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carroRbnActionPerformed(evt);
            }
        });

        motoRbn.setText("Moto");
        motoRbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motoRbnActionPerformed(evt);
            }
        });

        remolqueCheck.setText("Tiene remolque?");

        jLabel4.setText("Remolque");

        jLabel5.setText("Nro Cascos");

        confirmarBtn.setText("Confirmar Ingreso");
        confirmarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarBtnActionPerformed(evt);
            }
        });

        cancelarBtn.setText("Cancelar");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(parquederoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(placaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cancelarBtn)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(remolqueCheck)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(carroRbn)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(motoRbn))
                                                .addComponent(cascosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(confirmarBtn))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(parquederoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(placaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(carroRbn)
                            .addComponent(motoRbn))
                        .addGap(18, 18, 18)
                        .addComponent(remolqueCheck))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cascosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(confirmarBtn)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(cancelarBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void motoRbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motoRbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motoRbnActionPerformed

    private void carroRbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carroRbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carroRbnActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        //cerrar esta ventana
        this.setVisible(false);
    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void confirmarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarBtnActionPerformed
        //bucar un cubiculo disponible en el parqueadero
        int index = this.parqueadero.encontrarCubiculo();
        
        //crear un nuevo cubiculo y almacenar el vehiculo y darle la hora de ingreso que se toma automaticamente con new Date()
        Cubiculo cubiculo = new Cubiculo(this.vehiculo, new Date());
        //guardar el cubiculo en el parqueadero
        parqueadero.setCubiculo(index, cubiculo);
        //actualizar la informacion de cubiculos en la interfaz de parqueaderos
        parqueadero.actualizarInformacion();
        //cerrar esta ventana
        this.setVisible(false);
    }//GEN-LAST:event_confirmarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioConfirmacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioConfirmacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioConfirmacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioConfirmacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioConfirmacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JRadioButton carroRbn;
    private javax.swing.JTextField cascosTxt;
    private javax.swing.JButton confirmarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton motoRbn;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JLabel parquederoNombre;
    private javax.swing.JTextField placaTxt;
    private javax.swing.JCheckBox remolqueCheck;
    // End of variables declaration//GEN-END:variables
}
